In [ ]:
pip install numpy

pip install pandas

pip install matplotlib

pip install sklearn

In [18]:
pip install scikit-learn

     ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
     ---------------------------------------- 0.1/10.6 MB 3.3 MB/s eta 0:00:04
     - -------------------------------------- 0.5/10.6 MB 6.2 MB/s eta 0:00:02
     ---- ----------------------------------- 1.3/10.6 MB 10.5 MB/s eta 0:00:01
     -------- ------------------------------- 2.2/10.6 MB 12.7 MB/s eta 0:00:01
     ----------- ---------------------------- 3.1/10.6 MB 14.1 MB/s eta 0:00:01
     -------------- ------------------------- 4.0/10.6 MB 14.8 MB/s eta 0:00:01
     ----------------- ---------------------- 4.8/10.6 MB 15.2 MB/s eta 0:00:01
     --------------------- ------------------ 5.7/10.6 MB 15.8 MB/s eta 0:00:01
     ------------------------ --------------- 6.6/10.6 MB 16.2 MB/s eta 0:00:01
     ---------------------------- ----------- 7.5/10.6 MB 16.5 MB/s eta 0:00:01
     ------------------------------- -------- 8.4/10.6 MB 16.9 MB/s eta 0:00:01
     ----------------------------------- ---- 9.3/


[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: C:\Users\A5149\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Data Preprocessing

In [2]:
# Importing Libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Importing dataset

dataset = pd.read_csv('Data.csv')
print(dataset)
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
print("X = ",X)
print("Y = ",Y)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
X =  [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Y =  ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
# Taking Care of Missing Data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
# Encoding Categorical Data

#Independent Variable Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print("X = ",X)

#Dependent Variable Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y=le.fit_transform(Y)
print("Y = ",Y)

X =  [[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
Y =  [0 1 0 0 1 1 0 1 0 1]


In [9]:
#Split Data into Training Set & Test Set

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)
print("Training data X :\n",X_train)
print("Testing data X :\n",X_test)
print("Training data Y :\n",Y_train)
print("Testing data Y :\n",Y_test)

Training data X :
 [[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
Testing data X :
 [[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
Training data Y :
 [0 1 0 0 1 1 0 1]
Testing data Y :
 [0 1]


In [10]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])
print("Training data X :\n",X_train)
print("Testing data X :\n",X_test)

Training data X :
 [[1.0 0.0 0.0 1.2909944487358056 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 1.0 -0.7745966692414834 -0.014117293757057777
  -0.07013167641635372]
 [0.0 1.0 0.0 -0.7745966692414834 0.566708506533324 0.633562432710455]
 [1.0 0.0 0.0 1.2909944487358056 -0.30453019390224867
  -0.30786617274297867]
 [1.0 0.0 0.0 1.2909944487358056 -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 -0.7745966692414834 1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.0 -0.7745966692414834 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7401495441200351 -0.5646194287757332]]
Testing data X :
 [[1.0 0.0 1.0 -0.7745966692414834 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 -0.7745966692414834 -0.44973664397484414 0.2056403393225306]]
